server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_test
    username: root
    password: 123
  application:
    name: user-service-0301
mybatis:
  type-aliases-package: com.dev.pojo
logging:
  level:
    com:
      dev: debug
#########HuYi######
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
