server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_test
    username: root
    password: 123
  application:
    name: user-service-0301

mybatis:
  type-aliases-package: com.dev.pojo

logging:
  level:
    com:
      dev: debug

######################下面是关于eureka注册中心，eureka-client客户端的配置#######################
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找

##################这样就完成了此服务在注册中心的注册和拉取，以及动态更新状态##################################