server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_test
    username: root
    password: 123

mybatis:
  type-aliases-package: com.dev.pojo

logging:
  level:
    com:
      dev: debug